### ISSUE TITLE
Components folders structure

### ISSUE THREAD

**Issue by iuriizaporozhets** [olavoparno/github-surfer#1]
In the task was written to build domain driven project architecture. Current flat structure of the components folder could become a mess from the scalability perspective. Could you revisit this part please? Thanks

**Comment by olavoparno** [comment]
Thank you @iuriizaporozhets :) I will look into it as soon as possible.

**Comment by olavoparno** [comment]
Hello again, as it is pretty straightforward and there were lots of changes, I didn't open up a PR but rather commited to the very main. Please do check the folder structure again.

**Comment by iuriizaporozhets** [comment]
Hello, yes, sure, there was no need in separate PR.
